### ISSUE TITLE
PowerUps

### ISSUE THREAD

**Issue by BCorbin825** [FSanchez-UF/Galactic-Glide#5]
- [x] Add power up UI to the game (a visual indicator of what power ups the player has and how many)
- [x] Add score multiplier power up to game
- [x] We need to brainstorm ideas on how the player gets this score multiplier

**Comment by jgionti** [comment]
Implemented score multiplier powerup, but made it a permanent effect. It only spawns from bosses with a 50% chance right now when the player is at full HP (instead of spawning a heart), so it's kind of a reward for their skill. If that's fine, then this issue is good to close.
